
language: generic
arch: 
  - arm64
  - amd64
  - ppc64le
os: linux
dist: xenial

env:
  global:
  - RELEASE=xenial
  - GRADLE_VERSION=5.3.1 JAVA_VERSION=openjdk8

before_install:

install:

before_script:

jdk:
  - openjdk8

script:
  - sleep 1h
  - __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &
  - jdk_switcher use oraclejdk8
  - java --version
